version: "3"
services:
  pgdb:
    container_name: pgdb
    # use latest official postgres version
    image: "postgres:15.3"
    env_file:
      # configure postgres
      - ../postgres/database.env
    expose:
      - "5432"
    volumes:
      # persist data even if container shuts down
      - pgdb:/var/lib/postgresql/data/
      # run init sql script to create tables
      - ../postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - net

  api:
    container_name: api
    build: .
    image: dv4all/todo-flask-api:0.0.3
    env_file:
      # configure flask api
      - ./todo_api.env
    expose:
      - "5001"
    networks:
      - net
    depends_on:
      - pgdb

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8087:80"
      # proxy server for development
      # enable it in nginx.config and here
      # - "5001:5001"
    depends_on:
      - pgdb
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./next-food/out:/usr/share/nginx/html
    networks:
      - net

networks:
  net:

# named volumes can be managed easier using docker-compose
volumes:
  pgdb:
