version: '3'
services:
  pgdb:
    container_name: pgdb
    # use latest official postgres version
    image: "postgres:15.3"
    env_file:
      # configure postgres
      - ../postgres/database.env
    expose:
      - "5432"
    volumes:
      - todo_data:/var/lib/postgresql/data
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
  hasura:
    container_name: hasura
    # image: hasura/graphql-engine:v1.3.1.cli-migrations-v2
    image: hasura/graphql-engine:v2.33.4.cli-migrations-v2
    ports:
      - "8088:8088"
    depends_on:
      - "pgdb"
    restart: always
    volumes:
      # mount migration script (create tables)
      - ./hasura/migrations:/hasura/migrations
      # mount metadata info
      - ./hasura/metadata:/hasura/metadata
    environment:
      HASURA_GRAPHQL_SERVER_PORT: 8088
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura/migrations
      HASURA_GRAPHQL_METADATA_DIR: /hasura/metadata
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:changeme@pgdb:5432/todo_db
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, query-log
      # HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    networks:
      - net

networks:
  net:

volumes:
  todo_data: