version: "3"
services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    command: /bin/bash /home/mssql/entrypoint.sh
    env_file:
      # configure mssql
      - ./mssql/database.env
    expose:
      - "1433"
    volumes:
      # persist data
      - todo_data:/var/opt/mssql
      # run init sql scripts
      - ./mssql/entrypoint.sh:/home/mssql/entrypoint.sh
      - ./mssql/init.sh:/home/mssql/init.sh
      - ./mssql/init.sql:/home/mssql/init.sql
    networks:
      - net

  dotnet-todo-api:
    container_name: dotnet-todo-api
    build:
      context: ./
      dockerfile: Dockerfile
    image: dv4all/dotnet-todo-api:0.0.1
    ports:
      - "5000:80"
    networks:
      - net
    depends_on:
      - mssql

networks:
  net:

volumes:
  todo_data:

