version: '3'
services:
  pgdb:
    container_name: pgdb
    # use latest official postgres version
    image: "postgres:15.3"
    env_file:
      # configure postgres
      - ../postgres/database.env
    expose:
      - "5432"
    volumes:
      # persist data even if container shuts down
      - pgdb:/var/lib/postgresql/data/
      # run init sql script to create tables
      - ../postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - net

  todo-api:
    container_name: todo-api
    build: .
    image: dv4all/todo-fast-api:0.0.3
    environment:
      GUNICORN_CMD_ARGS: --bind=0.0.0.0:8086 --workers=4 --worker-class=uvicorn.workers.UvicornWorker
      API_ENV: production
      API_PORT: 8086
      API_NAME: todo-fast-api
      API_RELOAD: "False"
      API_DEBUG: "False"
      API_LOG_LEVEL: trace
      API_WORKERS: 4
      PG_HOST: pgdb
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASS: changeme
      PG_DB: todo_db
      PG_POOL_MAX_SIZE: 30
    expose:
      - "5432"
    ports:
      - "8086:8086"
    networks:
      - net
    depends_on:
      - pgdb

networks:
  net:

# named volumes can be managed easier using docker-compose
volumes:
  pgdb: