FROM node:12-alpine3.12 as build

WORKDIR /home/dv4all

COPY ./package*.json ./

RUN npm install

COPY . .

# RUN npm test
RUN npm run build

FROM alpine:3.12

WORKDIR /home/dv4all

RUN apk add --no-cache nodejs

# link to proper libc library
RUN ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2

COPY --from=build /home/dv4all/dist .
COPY ./deps/uws_linux_x64_83.node .

CMD ["node","index.js"]



