FROM golang:1.21 AS build

# install build tools
# RUN apk add --update gcc musl-dev

WORKDIR /app

COPY . .

RUN go build -o=todoapi

# RELEASE image
# there is problem when using multiple processes in fiber and DEBIAN image
# https://github.com/gofiber/fiber/issues/1036
# FROM debian:12

# RUN apt update && \
  # apt install curl -y

FROM golang:1.21

WORKDIR /app

COPY --from=build /app/todoapi /app/
COPY ./static /app/static

EXPOSE 5432
# EXPOSE 8080

CMD ./todoapi

