FROM oven/bun:1.0.1

WORKDIR /app

COPY package.json .
COPY bun.lockb .

RUN bun install --production
# RUN bun install --production

COPY src src
COPY tsconfig.json .
# COPY public public

ENV NODE_ENV production

CMD ["bun", "src/index.ts"]
