FROM node:20-slim as build

WORKDIR /home/dv4all

COPY ./package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM node:20-slim

WORKDIR /home/dv4all

COPY --from=build /home/dv4all/dist .

CMD ["node","index.js"]
